name: 'Fast Branch Creation without Checkout'
description: 'Create git branches instantly using GitHub API without checkout. Supports any ref and cross-repository creation.'
author: 'Songmu'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  token:
    description: 'GitHub token with write access to the repository'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'The name of the branch to create'
    required: true
  ref:
    description: 'The ref (branch/tag/commit) to create the new branch from'
    required: false
    default: ${{ github.ref }}
outputs:
  created:
    description: 'Whether the branch was created (true) or already existed (false)'
    value: ${{ steps.create.outputs.created }}
runs:
  using: 'composite'
  steps:
    - name: Create branch
      id: create
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_REF: ${{ inputs.ref }}
